### PR TITLE
Work around an issue with ASM rewriting types with names starting with $

### PR DESCRIPTION
**Pull request by bddckr**
See https://github.com/Kotlin/kotlinx.serialization/issues/2285 for more info.

### CODE REVIEW

**Comment by bddckr** [comment]
I ran into the linked issue. As explained in there, the bug is actually with ASM, kinda. However, considering that HiddenApiRefinePlugin is one of the special plugins in the Android ecosystem as it instruments not only symbols that were explicitly annotated, I've started to apply the workaround found in this PR.

Feel free to close this PR without merging it! I'm just sharing this in case it's helpful!

**Comment by bddckr** [comment]
I'm marking this PR as ready for review while waiting on what the maintainers of ASM think about this problem. I've opened an issue with them [here](https://gitlab.ow2.org/asm/asm/-/issues/317999).

I will raise another PR once/if ASM fixes the problem on their side. In the meantime, this PR unblocks anyone running into this issue.

---

You might be wondering: Why are other Android instrumentation plugins seemingly not running into this problem? Android's `transformClassesWith` will instantiate and call the given `AsmClassVisitorFactory`. `HiddenApiRefinePlugin` is exceptional in that it overrides `isInstrumentable` always to return `true` - it wants to potentially instrument _all_ classes. Other plugins only do that for _specific_ classes (annotated with the plugin-specific annotation(s)). 

---

I've added this plugin's Gradle project via `includeBuild` into my projects, but I'm running into issues with the Android Gradle Plugin's Lint tasks. They attempt to look up the dependencies of the build, which includes this plugin as a local copy now... but that fails with some cryptic issues. However, I can confirm that it doesn't fail if I use this plugin's released version. So I'm hoping that a new release of this plugin, with this PR's changes merged, would resolve that issue and allow me to continue to work with it in my projects (the Lint task is a mandatory check in my CI).

**Comment by bddckr** [comment]
[The ASM maintainers have decided that they won't fix this](https://gitlab.ow2.org/asm/asm/-/issues/317999#note_7), so this PR is needed for this plugin to work correctly when using Kotlin Serialization.

**Comment by Kr328** [comment]
I apologize for the delayed review of your Pull Request. Could you please rebase the main branch :)

**Comment by bddckr** [comment]
@Kr328 No worries! I've updated the branch.

**Pull request merged**
