### PR TITLE
Also transform unit and instrumentation tests

### LINKED ISSUE #18: Plugin version 4.0.0 no longer transforms unit and instrumentation test components
I believe all that's needed is to change this
https://github.com/RikkaApps/HiddenApiRefinePlugin/blob/b06bb6714f49aeccc11141265c630c8a00e4b210/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java#L23-L30

to also transform the `unitTest` and `androidTest` components of the `variant`.

### PR DESCRIPTION
**Pull request by bddckr**
Fixes #18.

### CODE REVIEW

**Comment by RikkaW** [comment]
```patch
Subject: [PATCH] Also transform unit and instrumentation tests
---
Index: gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java b/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java
--- a/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java	(revision b06bb6714f49aeccc11141265c630c8a00e4b210)
+++ b/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java	(date 1675431029932)
@@ -2,12 +2,15 @@
 
 import com.android.build.api.instrumentation.InstrumentationScope;
 import com.android.build.api.variant.AndroidComponentsExtension;
+import com.android.build.api.variant.Component;
+import com.android.build.api.variant.HasAndroidTest;
 import kotlin.Unit;
 import org.gradle.api.GradleException;
 import org.gradle.api.Plugin;
 import org.gradle.api.Project;
 
 import javax.annotation.Nonnull;
+import javax.annotation.Nullable;
 
 /**
  * Gradle plugin that do the class rename works.
@@ -22,11 +25,21 @@
 
         final AndroidComponentsExtension<?, ?, ?> components = target.getExtensions().getByType(AndroidComponentsExtension.class);
         components.onVariants(components.selector().all(), variant -> {
-            variant.getInstrumentation().transformClassesWith(
+            configureComponent(variant);
+            configureComponent(variant.getUnitTest());
+            if (variant instanceof HasAndroidTest) {
+                configureComponent(((HasAndroidTest) variant).getAndroidTest());
+            }
+        });
+    }
+
+    private void configureComponent(@Nullable final Component component) {
+        if (component != null) {
+            component.getInstrumentation().transformClassesWith(
                     RefineFactory.class,
                     InstrumentationScope.ALL,
                     (parameters) -> Unit.INSTANCE
             );
-        });
+        }
     }
 }
```

Tried to simplified the code.

**Comment by bddckr** [comment]
Thanks for that! I pushed another commit with that.

**Comment by alladdinstor-tech** [comment]
Zmzmj

**Comment by alladdinstor-tech** [comment]
Ajdhks JB ka

**Comment by alladdinstor-tech** [comment]
91ohwk30

**Comment by perosoales-spec** [comment]
Subject: [PATCH] Also transform unit and instrumentation tests
---
Index: gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java b/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java
--- a/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java	(revision b06bb6714f49aeccc11141265c630c8a00e4b210)
+++ b/gradle-plugin/src/main/java/dev/rikka/tools/refine/RefinePlugin.java	(date 1675431029932)
@@ -2,12 +2,15 @@
 
 import com.android.build.api.instrumentation.InstrumentationScope;
 import com.android.build.api.variant.AndroidComponentsExtension;
+import com.android.build.api.variant.Component;
+import com.android.build.api.variant.HasAndroidTest;
 import kotlin.Unit;
 import org.gradle.api.GradleException;
 import org.gradle.api.Plugin;
 import org.gradle.api.Project;
 
 import javax.annotation.Nonnull;
+import javax.annotation.Nullable;
 
 /**
  * Gradle plugin that do the class rename works.
@@ -22,11 +25,21 @@
 
         final AndroidComponentsExtension<?, ?, ?> components = target.getExtensions().getByType(AndroidComponentsExtension.class);
         components.onVariants(components.selector().all(), variant -> {
-            variant.getInstrumentation().transformClassesWith(
+            configureComponent(variant);
+            configureComponent(variant.getUnitTest());
+            if (variant instanceof HasAndroidTest) {
+                configureComponent(((HasAndroidTest) variant).getAndroidTest());
+            }
+        });
+    }
+
+    private void configureComponent(@Nullable final Component component) {
+        if (component != null) {
+            component.getInstrumentation().transformClassesWith(
                     RefineFactory.class,
                     InstrumentationScope.ALL,
                     (parameters) -> Unit.INSTANCE
             );
-        });
+        }
     }
 }

**Pull request merged**
